// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models.HarmanTarimDB;

namespace WebApplication2.Migrations.HarmanTarim
{
    [DbContext(typeof(HarmanTarimContext))]
    [Migration("20201104140632_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Models.DHarmanTarimDBevDB.Agreements", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("Date");

                    b.Property<bool>("fr_certificate")
                        .HasColumnType("Bit");

                    b.Property<int>("grower_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("agreements");
                });

            modelBuilder.Entity("WebApplication2.Models.DHarmanTarimDBevDB.Declarations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("agreement_id")
                        .HasColumnType("int");

                    b.Property<double>("average_efficiency")
                        .HasColumnType("Float");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("Date");

                    b.Property<DateTime>("date1")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("date2")
                        .HasColumnType("datetime");

                    b.Property<string>("declaration_id")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("efficiency")
                        .HasColumnType("Float");

                    b.Property<bool>("fr_certificate")
                        .HasColumnType("Bit");

                    b.Property<DateTime>("harvest_end")
                        .HasColumnType("Date");

                    b.Property<DateTime>("harvest_start")
                        .HasColumnType("Date");

                    b.Property<int>("total_area")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("declarations");
                });

            modelBuilder.Entity("WebApplication2.Models.HarmanTarimDB.Agreement_Factories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("agreement_id")
                        .HasColumnType("int");

                    b.Property<int>("agreement_items_id")
                        .HasColumnType("int");

                    b.Property<int>("factory_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("agreement_factories");
                });

            modelBuilder.Entity("WebApplication2.Models.HarmanTarimDB.Agreement_Items", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("agreement_id")
                        .HasColumnType("int");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("total_price")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("agreement_items");
                });

            modelBuilder.Entity("WebApplication2.Models.HarmanTarimDB.Factories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("country_code")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("Date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fax")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("landline")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("factories");
                });

            modelBuilder.Entity("WebApplication2.Models.HarmanTarimDB.Fields", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("area")
                        .HasColumnType("int");

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<string>("continent")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("grower_id")
                        .HasColumnType("int");

                    b.Property<int>("lot")
                        .HasColumnType("int");

                    b.Property<int>("parcel")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("fields");
                });

            modelBuilder.Entity("WebApplication2.Models.HarmanTarimDB.Growers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GovermentID")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("address2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("coa_number")
                        .HasColumnType("int");

                    b.Property<int>("country_code")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("Date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mobile2")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("growers");
                });

            modelBuilder.Entity("WebApplication2.Models.HarmanTarimDB.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("accounted_amount")
                        .HasColumnType("Float");

                    b.Property<double>("average_efficiency")
                        .HasColumnType("Float");

                    b.Property<double>("average_grams")
                        .HasColumnType("Float");

                    b.Property<double>("average_price")
                        .HasColumnType("Float");

                    b.Property<double>("average_red_amount")
                        .HasColumnType("Float");

                    b.Property<bool>("diagnosis")
                        .HasColumnType("Bit");

                    b.Property<double>("dry_amount")
                        .HasColumnType("Float");

                    b.Property<double>("efficiency_weight")
                        .HasColumnType("Float");

                    b.Property<double>("estimated_cert_amount")
                        .HasColumnType("Float");

                    b.Property<string>("kind")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("not_accounted_amount")
                        .HasColumnType("Float");

                    b.Property<DateTime>("production_year")
                        .HasColumnType("Date");

                    b.Property<double>("total_amount")
                        .HasColumnType("Float");

                    b.Property<double>("total_red_amount")
                        .HasColumnType("Float");

                    b.Property<string>("variety")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("wet_amount")
                        .HasColumnType("Float");

                    b.HasKey("id");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
